variables:
    PLUGIN_NAME: 'authorsIndex'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: stable-3_4_0
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs/cypress_tests.yml'


